name: EvatunaHello
version: '${version}'
main: kr.kua.evatunahello.Main
api-version: 1.18
authors: [ Kua ]
depend: [Litebans]
website: https://evatuna.fish

commands:
  evatunahello:
    description: reload config